Patient/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import PatientListView, PatientCreateView, PatientDetailView, PatientUpdateView, PatientDeleteView

app_name = 'Patient'

urlpatterns = [
    path('api/', include('Patient.api.urls', namespace='api')),
    path('list/', PatientListView.as_view(), name='list'),
    path('create/', PatientCreateView.as_view(), name='create'),
    path('<int:pk>/', PatientDetailView.as_view(), name='detail'),
    path('<int:pk>/update', PatientUpdateView.as_view(), name='update'),
    path('<int:pk>/delete', PatientDeleteView.as_view(), name='delete'),
]

Tabib/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from .views import HomeView
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('patient/', include('Patient.urls', namespace='patient')),
    path('consultation/', include('Consultation.urls', namespace='consultation')),
    path('controle/', include('Controle.urls', namespace='controle')),
    path('admin/', admin.site.urls),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='login.html')),
    path('accounts/', include('django.contrib.auth.urls')),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
  <html>
    <head>
      <link rel="icon" href={% static "img/favicon.ico" %}>
      <link rel="stylesheet" href="{% static 'lib/bootstrap/css/bootstrap.min.css' %}" >
      <link rel="stylesheet" href="{% static 'lib/fontawesome/css/all.min.css' %}">
      <link rel="stylesheet" href="{% static 'styles/base/base.css' %}" >
      <style media="screen">
      body{
        background-image: url("{% static 'img/bg1.jpg' %}");
        background-repeat: round;
      }
      </style>
      {% block css %}{% endblock %}
      <title>{% block title %} Tabib  {% endblock %}</title>
    </head>

    <body>
      {% include "navbar.html" with user=request.user %}
      <div class="container-fluid" id="page-container">
        <a class="to-hide-on-login" onclick="history.go(-1)" style="cursor: pointer;"> <i class="fas fa-arrow-circle-left fa-3x"></i> </a>
        <a class="to-hide-on-login" onclick="history.go(+1)"style="float: right;cursor: pointer;" > <i class="fas fa-arrow-circle-right fa-3x"></i> </a>
 
        <div id="page-wrapper">
          <br><br><br>
          {% block container %}{% endblock %}
          <br><br><br>
        </div>
      </div>

      {% include "footer.html" %}

      <script src="{% static 'lib/jquery/jquery.min.js' %}"></script>
      <script src="{% static 'lib/bootstrap/js/bootstrap.min.js' %}"></script>
      {% block script %}

      {% endblock %}
    </body>
  </html>

templates/footer.html
<style media="screen">
  .down{
    margin-bottom: -10px;
  }
</style>

 <footer class="container-fluid container-contact-us">
     <div class="row">
         <div class="col-10 offset-1">
           <div class="row">
             <div class="col-3 offset-1 down">
               <i class="fa fa-map-marker"></i>
               <span>Alger, Ben Aknoun</span>
             </div>
             <div class="col-3 offset-1 down">
               <i class="fa fa-phone"></i>
               <span>+213 541 543 357</span>
             </div>
             <div class="col-3 offset-1 down">
               <i class="fa fa-envelope"></i> Email:
               <span>fc_harouit@esi.dz</span>
             </div>
           </div>
           <hr>
         </div>
     </div>
 </footer>

templates/home.html
{% extends "base.html" %}
{% load dict_key %}
{% load last_visite %}
{% block css %}
  <style >
    .table-wrapper-scroll-y {
      display: block;
      max-height: 600px;
      overflow-y: auto;
      -ms-overflow-style: -ms-autohiding-scrollbar;
    }

    .rdv-div{
      border-style: dashed;
    }

    .red{
      color: red;
    }
  </style>
{% endblock %}

{% block container %}
<div class="row">
  <div class="col-10 offset-1">
    <h2>Liste des Rendez-vous proches</h2> <br> <br>
    <div class="row">
      {% for date in dates %}
          <div class="col-6 border border-dark rounded">
            <b></b>
            RDV le <b> {{date}}</b> avec:<br><br>
            <div class="table-wrapper-scroll-y">
              <table  class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
                 <thead class="thead-light">
                   <tr>
                     <th>Patient</th>
                     <th>Dernière visite</th>
                     <th></th>
                   </tr>
                 </thead>
                 <tbody>
                    {% for visite in rdvsCons|dict_key:date %}
                      <tr>
                        <td>{{visite.patient}} <a data-toggle="tooltip" data-placement="left" title="Patient {{visite.patient}}" href="{{visite.patient.get_detail_url}}"><i class="fas fa-user-injured fa-2x"></i></a></td>
                        <td>{{visite.patient|last_visite}}</td>
                        <td> <a data-toggle="tooltip" data-placement="left" title="{{visite}}" href="{{visite.get_detail_url}}" href="{{visite.get_detail_url}}"><i class="fas fa-notes-medical fa-2x"></i></a>
                          {% if visite.a_operer %}
                            <i class="fas fa-procedures fa-2x red pulse"></i>
                          {% endif %}
                        </td>
                      </tr>
                    {% endfor %}
                    {% for visite in rdvsCtrl|dict_key:date %}
                      <tr>
                        <td>{{visite.consultation.patient}} <a data-toggle="tooltip" data-placement="left" title="Patient {{visite.consultation.patient}}" href="{{visite.consultation.patient.get_detail_url}}"><i class="fas fa-user-injured fa-2x"></i></a></td>
                        <td>{{visite.consultation.patient|last_visite}}</td>
                        <td> <a data-toggle="tooltip" data-placement="left" title="{{visite}}" href="{{visite.get_detail_url}}"><i class="fas fa-stethoscope fa-2x"></i></i></a>
                          {% if visite.a_operer %}
                            <i class="fas fa-procedures fa-2x red pulse"></i>
                          {% endif %}
                        </td>
                      </tr>
                    {% endfor %}
                 </tbody>
               </table>
            </div>
          </div>
      {% endfor %}
    </div>
  </div>
</div>

{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block title %} {{block.super}} Connexion{% endblock title %}

{% block css %}
<style media="screen">
  .login-div{
    background-color : rgba(250,250,250,0.8);
    border-radius : 20px;
  }
</style>
{% endblock css %}

{% block container %}
<div class="row">
  <div class="offset-4 text-center  col-4 login-div">
    <br>

    <h1> Se connecter </h1>
  {% if form.errors %}
  <p style="color:red">Erreur. votre nom d'utilisateur ou mot de passe est incorrect</p>
  {% endif %}

  {% if next %}
      {% if user.is_authenticated %}
      <script type="text/javascript">
        window.history.back();
      </script>
      <p>Vous n'avez pas l'accès</p>
      {% else %}
      <p>Connectez-vous pour continuer.</p>
      {% endif %}
  {% endif %}

  <form id="login-form" method="post" action="{% url 'login' %}">
  {% csrf_token %}

  <div class="form-group">
    {{ form.username.label_tag }}<br>
    {{ form.username }}
  </div>
  <div class="form-group">
    {{ form.password.label_tag }}<br>
    {{ form.password }}
  </div>

    <button type="submit" class="btn btn-outline-success">Connexion </button>
    <br><br><br>
  </form>
  <!--
  {# Assumes you setup the password_reset view in your URLconf #}
  <p><a href="{% url 'password_reset' %}">mot de passe perdu ? (pas encore traité)</a></p> -->
  </div>

</div>
{% endblock container %}

templates/navbar.html
{% load static %}

<style media="screen">
  a.disabled:not([href]){
    color: gray;
  }
  a.disabled:not([href]):hover{
    color: gray;
  }
</style>
    <nav id="navbar" class=" navbar navbar-expand-lg home-navbar navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'home' %}"><i class="fas fa-clinic-medical fa-2x"></i></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div id="navbarNavDropdown" class="navbar-collapse collapse">
            <ul class="navbar-nav mr-auto">
                
                <li class="nav-item dropdown">
                    <a href="" class="nav-link " data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Patients <i class=" fas fa-angle-down"></i>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                      {% if user.is_authenticated %}
                      <a class="dropdown-item" href="{% url 'patient:list' %}"><i class="fas fa-list" ></i> Liste des patients</a>
                      <a class="dropdown-item" href="{% url 'patient:create' %}"><i class="fas fa-user-plus"></i> Nouveau patient</a>
                      {% else %}
                      <a class="dropdown-item disabled" ><i class="fas fa-list" ></i> Liste des patients</a>
                      <a class="dropdown-item disabled" ><i class="fas fa-user-plus"></i> Nouveau patient</a>
                      {% endif %}

                    </div>
                </li>
            </ul>
            <ul class="navbar-nav">
              <li class="nav-item active" style="margin-left:auto;">
                  <a href='' class="location-navigation" onclick="location.reload()" style="color: #f4f4f4;"><i class=" fas fa-redo fa-2x location-navigation-btn"></i></a>
              </li>

              {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a href="" class="nav-link " data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      {% if user.is_superuser %}
                      {{user}}
                      {% else %}
                      Dr. {{user.last_name}} {{user.first_name}}  <i class=" fas fa-angle-down"></i>
                      {% endif %}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                      {% if user.is_superuser %}
                        <a class="dropdown-item" href="{% url 'admin:index' %}">Administrer</a>
                      {% else %}
                        <a class="dropdown-item disabled">Administrer</a>
                      {% endif %}
                        <a class="dropdown-item" href="{% url 'logout' %}">Se déconnecter</a>
                    </div>
                </li>
              {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Se connecter</a>
                </li>
              {% endif %}
            </ul>
        </div>
    </nav>